export const CATEGORIES_FETCHED = "CATEGORIES_FETCHED";
export const CATEGORIES_ERROR = "CATEGORIES_ERROR";

export const ITEMS_FETCHED = "ITEMS_FETCHED";
export const ITEMS_ERROR = "ITEMS_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
