export const CATEGORIES_FETCHED = "CATEGORIES_FETCHED";
export const CATEGORIES_ERROR = "CATEGORIES_ERROR";

export const ITEMS_FETCHED = "ITEMS_FETCHED";
export const ITEMS_ERROR = "ITEMS_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const ADMIN_LOGGEDIN = "ADMIN_LOGGEDIN";
export const ADMIN_LOADED = "ADMIN_LOADED";
export const ADMIN_ERROR = "ADMIN_ERROR";

export const CART_FETCHED = "CART_FETCHED";
export const ADDED_TO_CART = "ADDED_TO_CART";
export const REMOVED_FROM_CART = "REMOVED_FROM_CART";
export const CART_ERROR = "CART_ERROR";
export const CLEAR_CART = "CLEAR_CART";

export const PROFILE_UPDATED = "PROFILE_UPDATED";
export const PROFILE_PIC_UPDATED = "PROFILE_PIC_UPDATED";
export const PROFILE_ERROR = "PROFILE_ERROR";

export const ORDERS_FETCHED = "ORDERS_FETCHED";
export const ORDER_DETAIL_FETCHED = "ORDER_DETAIL_FETCHED";
export const ORDER_CREATED = "ORDER_CREATED";
export const ORDER_CANCELED = "ORDER_CANCELED";
export const ORDER_PAID = "ORDER_PAID";
export const ORDER_ERROR = "ORDER_ERROR";
export const CLEAR_ORDER = "CLEAR_ORDER";

export const CREATE_TOAST = "CREATE_TOAST";
export const CLEAR_TOAST = "CLEAR_TOAST";
